# Part 2.1: Introduction to Pandas

Pandas, Python programlama dili için yüksek performanslı, kullanımı kolay veri yapıları ve veri analizi araçları sağlayan açık kaynaklı bir kitaplıktır. R programlama dilinde bulunan veri çerçevesi kavramına dayanmaktadır. Bu sınıf için, Pandalar, sinir ağları tarafından işlenecek verileri işlemek için kullandığımız birincil araç olacaktır.

Veri çerçevesi, Pandaların önemli bir bileşenidir. Bunu auto-mpg veri kümesine erişmek için kullanacağız. Bu veri kümesini UCI makine öğrenimi havuzunda bulabilirsiniz. Bu sınıf için, sütun başlıklarını eklediğim Auto MPG veri setinin bir sürümünü kullanacağız. Sürümümü burada bulabilirsiniz.

UCI bu veri setini Carnegie Mellon Üniversitesi'nin sürdürdüğü StatLib kütüphanesinden aldı. Veri seti 1983 Amerikan İstatistik Derneği Sergisinde kullanıldı. MPG, silindirler, yer değiştirme, beygir gücü, ağırlık, hızlanma, model yılı, menşe ve otomobilin adı dahil 398 arabaya ait verileri içerir.

Aşağıdaki kod, MPG veri kümesini bir veri çerçevesine yükler:

In [2]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 302D-B73D

 Directory of C:\Users\hp\Desktop\t81_558_deep_learning-2020-spring\t81_558_deep_learning-2020-spring

14.01.2021  12:30    <DIR>          .
14.01.2021  12:30    <DIR>          ..
23.08.2020  23:56             1.647 .gitignore
13.01.2021  20:19    <DIR>          .ipynb_checkpoints
14.12.2020  19:03    <DIR>          assignments
23.08.2020  23:56            10.772 citations.bib
23.08.2020  23:56             3.351 CODE_OF_CONDUCT.md
23.08.2020  23:56    <DIR>          data
23.08.2020  23:56    <DIR>          images
23.08.2020  23:56    <DIR>          install
14.01.2021  12:30            46.176 Introduction to Pandas-2.1.ipynb
23.08.2020  23:56             6.699 jeffs_helpful.ipynb
23.08.2020  23:56            11.357 LICENSE
23.08.2020  23:56             7.108 manual_setup.ipynb
23.08.2020  23:56    <DIR>          pdf
23.08.2020  23:56               474 person.json
23.08.2020  23:56    <DIR>          photos
23.08.2020  2

In [51]:
# basit bir dataframe oluşturduk böyle, print fonksiyonu ile 
import os
import pandas as pd

df = pd.read_csv("auto-mpg.csv") # bir csv dosyasını okuma yapıyoruz pandas'ın function'ı ile 
print(df[0:5]) # burada ki de basit bir işlem 

    mpg  cylinders  displacement  ... year  origin                       name
0  18.0          8         307.0  ...   70       1  chevrolet chevelle malibu
1  15.0          8         350.0  ...   70       1          buick skylark 320
2  18.0          8         318.0  ...   70       1         plymouth satellite
3  16.0          8         304.0  ...   70       1              amc rebel sst
4  17.0          8         302.0  ...   70       1                ford torino

[5 rows x 9 columns]


In [7]:
display(df[0:5]) #display fonksiyonu ile de bunu yapabiliriz 

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0  18.0          8         307.0        130    3504          12.0    70   
1  15.0          8         350.0        165    3693          11.5    70   
2  18.0          8         318.0        150    3436          11.0    70   
3  16.0          8         304.0        150    3433          12.0    70   
4  17.0          8         302.0        140    3449          10.5    70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

** display** işlevi, yalnızca veri çerçevesini yazdırmaktan daha temiz bir görüntü sağlar. Maksimum satır ve sütunların belirtilmesi, ekran üzerinde daha fazla kontrole sahip olmanızı sağlar.

In [8]:
pd.set_option('display.max_columns', 7)
pd.set_option('display.max_rows', 5)
display(df)

mpg  cylinders  displacement  ... year  origin  \
0    18.0          8         307.0  ...   70       1   
1    15.0          8         350.0  ...   70       1   
..    ...        ...           ...  ...  ...     ...   
396  28.0          4         120.0  ...   82       1   
397  31.0          4         119.0  ...   82       1   

                          name  
0    chevrolet chevelle malibu  
1            buick skylark 320  
..                         ...  
396                ford ranger  
397                 chevy s-10  

[398 rows x 9 columns]

In [23]:
df.head() #pandas'ın daha basit bir komutu ile de bunu yapabiliriz

mpg  displacement  acceleration
0  18.0         307.0          12.0
1  15.0         350.0          11.5
2  18.0         318.0          11.0
3  16.0         304.0          12.0
4  17.0         302.0          10.5

In [48]:
df.cylinders

0      8
1      8
      ..
396    4
397    4
Name: cylinders, Length: 398, dtype: int64

Birinci veri çerçevesi hakkında istatistiksel bilgileri görüntülemek için ikinci bir veri çerçevesi oluşturmak mümkündür.

In [38]:
df

mpg  cylinders  displacement  weight  acceleration  year  origin
0    18.0          8         307.0    3504          12.0    70       1
1    15.0          8         350.0    3693          11.5    70       1
..    ...        ...           ...     ...           ...   ...     ...
396  28.0          4         120.0    2625          18.6    82       1
397  31.0          4         119.0    2720          19.4    82       1

[398 rows x 7 columns]

In [39]:
headers

['mpg',
 'cylinders',
 'displacement',
 'weight',
 'acceleration',
 'year',
 'origin']

In [16]:
fields

[{'name': 'mpg',
  'mean': 23.514572864321615,
  'var': 61.089610774274405,
  'sdev': 7.815984312565782},
 {'name': 'displacement',
  'mean': 193.42587939698493,
  'var': 10872.199152247364,
  'sdev': 104.26983817119581},
 {'name': 'acceleration',
  'mean': 15.568090452261291,
  'var': 7.604848233611381,
  'sdev': 2.7576889298126757}]

In [36]:
# Strip non-numerics
df = df.select_dtypes(include=['int64', 'float64']) # Dataframe'den integer ve float dönen verileri df içine aldık 

headers = list(df.columns.values) # bir liste haline getirdik
fields = [] # boş bir listee oluşturduk

for field in headers:  # her bir columns için döngü oluşturuyoruz
    fields.append({ # burada boş listenin içine aldığımız columnslara aşağıdakileri ekledik append function ile, dictionary oluşturduk 
        'name' : field, 
        'mean': df[field].mean(), # ortalama 
        'var': df[field].var(),  # varyansı
        'sdev': df[field].std() # standart sapma
    })

for field in fields:
    print(field)
    
#örneğin burada horsepower integer bir değer olmasına karşılık almadı çünkü horsepower object dönüyor DataFrame'de

{'name': 'mpg', 'mean': 23.514572864321615, 'var': 61.089610774274405, 'sdev': 7.815984312565782}
{'name': 'cylinders', 'mean': 5.454773869346734, 'var': 2.8934154399199943, 'sdev': 1.7010042445332094}
{'name': 'displacement', 'mean': 193.42587939698493, 'var': 10872.199152247364, 'sdev': 104.26983817119581}
{'name': 'weight', 'mean': 2970.424623115578, 'var': 717140.9905256768, 'sdev': 846.8417741973271}
{'name': 'acceleration', 'mean': 15.568090452261291, 'var': 7.604848233611381, 'sdev': 2.7576889298126757}
{'name': 'year', 'mean': 76.01005025125629, 'var': 13.672442818627143, 'sdev': 3.697626646732623}
{'name': 'origin', 'mean': 1.5728643216080402, 'var': 0.6432920268850575, 'sdev': 0.8020548777266163}


Bu kod, bu istatistiksel bilgileri tutan sözlüklerin bir listesini çıkarır. Bu bilgiler, Modül 1'de görülen JSON koduna benzer. JSON için doğru bir şekilde, program bu kayıtları bir listeye eklemeli ve Python JSON kitaplığının ** dumps ** komutunu çağırmalıdır.

Python programı, bu JSON benzeri bilgileri daha iyi görüntüleme için bir veri çerçevesine dönüştürebilir.

In [40]:
df2 = pd.DataFrame(fields)
display(df2)
# aslında aldığımız istatiksel bilgiler ile sıfırdan bir dataframe oluşturduğumuzu söyleyebilirim

name       mean        var      sdev
0         mpg  23.514573  61.089611  7.815984
1   cylinders   5.454774   2.893415  1.701004
..        ...        ...        ...       ...
5        year  76.010050  13.672443  3.697627
6      origin   1.572864   0.643292  0.802055

[7 rows x 4 columns]

## Missing Values

Eksik değerler, makine öğreniminin bir gerçeğidir. İdeal olarak, her veri satırı, tüm sütunlar için değerlere sahip olacaktır. Ancak bu nadiren böyledir. Değerlerin çoğu MPG veritabanında mevcuttur. Ancak beygir gücü sütununda eksik değerler var. Yaygın bir uygulama, eksik değerleri o sütun için medyan değerle değiştirmektir. Program medyanı [here] (https://www.mathsisfun.com/median.html) açıklandığı gibi hesaplar. Aşağıdaki kod, beygir gücündeki tüm NA değerlerini medyanla değiştirir:

In [58]:
df.horsepower.unique() 
# burada ? işaretini görebilirsiniz çünkü Na veya NAN dönmüyor onu da ekledik csv dosyasını okurken
# bu kısmı aşağıdaki code'u çalıştırdıktan sonra göremeyebilirsiniz çünkü aşağıda ki code'da medyan değerini koyduk yerine
# ama siz en baştaki okuma işlemini yapıp bu kodu çalıştırırsanız göreceksiniz ki "?" var

array([130. , 165. , 150. , 140. , 198. , 220. , 215. , 225. , 190. ,
       170. , 160. ,  95. ,  97. ,  85. ,  88. ,  46. ,  87. ,  90. ,
       113. , 200. , 210. , 193. ,  93.5, 100. , 105. , 175. , 153. ,
       180. , 110. ,  72. ,  86. ,  70. ,  76. ,  65. ,  69. ,  60. ,
        80. ,  54. , 208. , 155. , 112. ,  92. , 145. , 137. , 158. ,
       167. ,  94. , 107. , 230. ,  49. ,  75. ,  91. , 122. ,  67. ,
        83. ,  78. ,  52. ,  61. ,  93. , 148. , 129. ,  96. ,  71. ,
        98. , 115. ,  53. ,  81. ,  79. , 120. , 152. , 102. , 108. ,
        68. ,  58. , 149. ,  89. ,  63. ,  48. ,  66. , 139. , 103. ,
       125. , 133. , 138. , 135. , 142. ,  77. ,  62. , 132. ,  84. ,
        64. ,  74. , 116. ,  82. ])

In [57]:
import os
import pandas as pd

df = pd.read_csv(
    "auto-mpg.csv",  #aynı veri kümesini yükledik 
    na_values=['NA', '?']) # 
print(f"horsepower has na? {pd.isnull(df['horsepower']).values.any()}") # True dönüyor çünkü içinde "?"  var 
    
print("Filling missing values...")
med = df['horsepower'].median() # burada median değerini alıp med'e attık 
df['horsepower'] = df['horsepower'].fillna(med) # fillna function ile siz normalde 0 yapabilirsiniz ama biz medyan değerini koyduk
# df = df.dropna() # ayrıca basitçe NA değerlerini de bırakabilirsiniz bu function ile, tüm row'u silebilirsiniz 
                 
print(f"horsepower has na? {pd.isnull(df['horsepower']).values.any()}") # aynı komutu çalıştırdığımızda False olduğunu gördük

horsepower has na? True
Filling missing values...
horsepower has na? False


# Dealing with Outliers

Aykırı değerler, alışılmadık şekilde yüksek veya düşük değerlerdir. Bazen aykırı değerler sadece hatalardır; bu [observation error] 'nın (https://en.wikipedia.org/wiki/Observational_error) bir sonucudur. Aykırı değerler, ele alınması zor olabilecek gerçekten büyük veya küçük değerler de olabilir. Tipik olarak aykırı değerleri, ortalamadan birkaç standart sapma olan bir değer olarak kabul ederiz. Aşağıdaki işlev bu tür değerleri kaldırabilir.

In [60]:
# Belirtilen sütunun +/- sd standart sapmalar olduğu tüm satırları kaldırın
def remove_outliers(df, name, sd):
    drop_rows = df.index[(np.abs(df[name] - df[name].mean())
                          >= (sd * df[name].std()))]
    df.drop(drop_rows, axis=0, inplace=True)

In [59]:
df.index

RangeIndex(start=0, stop=398, step=1)

Aşağıdaki kod, beygir gücünün ortalamanın üzerinde veya altında ikiden fazla standart sapma olduğu her satırı Auto MPG veri kümesinden çıkaracaktır.

In [66]:
import pandas as pd
import os

df = pd.read_csv(
    "auto-mpg.csv",
    na_values=['NA','?'])

# özellik vektörü oluşturduk
med = df['horsepower'].median()
df['horsepower'] = df['horsepower'].fillna(med)

# name columns'ını kaldırdık
df.drop('name',1,inplace=True)

# horsepower'daki outliers'ları çıkardık
print("Length before MPG outliers dropped: {}".format(len(df)))
remove_outliers(df,'mpg',2)
print("Length after MPG outliers dropped: {}".format(len(df)))

pd.set_option('display.max_columns', 0)
pd.set_option('display.max_rows', 5)
display(df)

Length before MPG outliers dropped: 398
Length after MPG outliers dropped: 388


mpg  cylinders  displacement  ...  acceleration  year  origin
0    18.0          8         307.0  ...          12.0    70       1
1    15.0          8         350.0  ...          11.5    70       1
..    ...        ...           ...  ...           ...   ...     ...
396  28.0          4         120.0  ...          18.6    82       1
397  31.0          4         119.0  ...          19.4    82       1

[388 rows x 8 columns]

## Dropping Fields

Bazı alanların sinir ağı için hiçbir değeri yoktur, bırakılmalıdır. Aşağıdaki kod, name sütununu MPG veri kümesinden kaldırır.

In [64]:
import os
import pandas as pd

df = pd.read_csv(
    "auto-mpg.csv",
    na_values=['NA','?'])

print(f"Before drop: {list(df.columns)}")
df.drop('name', 1, inplace=True) # burada inplace=True olması tekrar eşitlik kurmadan değişikliği DataFrame'de uygulaması için
print(f"After drop: {list(df.columns)}")

Before drop: ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'year', 'origin', 'name']
After drop: ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'year', 'origin']


## Concatenating Rows and Columns
Python, yeni veri çerçeveleri oluşturmak için satırları ve sütunları bir araya getirebilir. Aşağıdaki kod, Auto MPG veri kümesindeki ** name ** ve ** horsepower ** sütunlarından yeni bir veri çerçevesi oluşturur. Program bunu iki sütunu bir araya getirerek yapar.

In [68]:
# Ad ve beygir gücünden yeni bir veri çerçevesi oluşturduk
# dummy variables'da işimize yarayacak diyebiliriz
import os
import pandas as pd

df = pd.read_csv(
    "auto-mpg.csv",
    na_values=['NA','?'])

col_horsepower = df['horsepower']
col_name = df['name']
result = pd.concat([col_name, col_horsepower], axis=1) # burada concat function ile iki sutunu birleştirdik

result.head()

name  horsepower
0  chevrolet chevelle malibu       130.0
1          buick skylark 320       165.0
2         plymouth satellite       150.0
3              amc rebel sst       150.0
4                ford torino       140.0

** concat ** işlevi aynı zamanda iki satırı birbirine bağlayabilir. Bu kod, Auto MPG veri kümesinin ilk iki satırını ve son iki satırını birleştirir.

In [69]:
# İlk 2 satırdan ve son 2 satırdan yeni bir veri çerçevesi oluşturun
import os
import pandas as pd

df = pd.read_csv(
    "auto-mpg.csv",
    na_values=['NA','?'])

result = pd.concat([df[0:2],df[-2:]], axis=0) #ilk 2 satır ile son 2 satırı birleştirdik 

result.head()

mpg  cylinders  displacement  ...  year  origin                       name
0    18.0          8         307.0  ...    70       1  chevrolet chevelle malibu
1    15.0          8         350.0  ...    70       1          buick skylark 320
396  28.0          4         120.0  ...    82       1                ford ranger
397  31.0          4         119.0  ...    82       1                 chevy s-10

[4 rows x 9 columns]

## Training and Validation

Bir makine öğrenimi modelini daha önce hiç görmediği verileri tahmin etme yeteneğine göre değerlendirmeliyiz. Bu nedenle, eğitim verilerini genellikle bir doğrulama ve eğitim setine böleriz. Makine öğrenimi modeli eğitim verilerinden öğrenecek, ancak nihayetinde doğrulama verilerine dayalı olarak değerlendirilecektir.

Training Data - In Sample Data - Sinir ağının eğitmek için kullandığı veriler.

Validation Data - Out of Sample Data- Makine öğrenimi modelinin eğitim verilerine uyduktan sonra değerlendirildiği veriler.
Eğitim ve doğrulama verilerini ele almanın iki etkili yolu vardır:

Training/Validation Split - Program, verileri eğitim ve doğrulama (tutma) seti arasındaki bir orana göre böler. Tipik oranlar% 80 eğitim ve %20 doğrulamadır.

K-Fold Cross Validation - Program, verileri birkaç kat ve modele böler. Program kıvrımlarla aynı sayıda model oluşturduğundan, program tüm veri kümesi için örneklem dışı tahminler üretebilir.
Aşağıdaki kod, MPG verilerinin bir eğitim ve doğrulama setine bölünmesini sağlar. Eğitim seti verilerin% 80'ini kullanır ve doğrulama seti% 20'sini kullanır. 


In [101]:
import os
import pandas as pd
import numpy as np

df = pd.read_csv(
    "auto-mpg.csv",
    na_values=['NA','?'])

# Genellikle karıştırmak için iyi bir fikir
df = df.reindex(np.random.permutation(df.index)) 

mask = np.random.rand(len(df)) < 0.8 # 0 ile 1 arasomda random sayılar oluşturduk ve bunun 0.8 altında olanları mask'e attık
trainDF = pd.DataFrame(df[mask])
validationDF = pd.DataFrame(df[~mask]) # ¨ geri kalan kısmı alıp dataframe'e çevirdik

print(f"Training DF: {len(trainDF)}")
print(f"Validation DF: {len(validationDF)}")

# bu code çalıştırdığınızda sürekli değişecektir çünkü 0.8 altında olanları alıyor sadece

Training DF: 303
Validation DF: 95


In [104]:
df[~mask] #aslında validationDF kadar bir dataframe döner bize 

mpg  cylinders  displacement  ...  year  origin                     name
396  28.0          4         120.0  ...    82       1              ford ranger
115  15.0          8         350.0  ...    73       1  chevrolet monte carlo s
..    ...        ...           ...  ...   ...     ...                      ...
205  28.0          4          97.0  ...    76       3           toyota corolla
72   15.0          8         304.0  ...    72       1         amc matador (sw)

[95 rows x 9 columns]

In [92]:
df.reindex(np.random.permutation(df.index)) 

mpg  cylinders  displacement  ...  year  origin               name
357  32.9          4         119.0  ...    81       3       datsun 200sx
172  25.0          4          90.0  ...    75       2  volkswagen dasher
..    ...        ...           ...  ...   ...     ...                ...
86   14.0          8         304.0  ...    73       1        amc matador
32   25.0          4          98.0  ...    71       1         ford pinto

[398 rows x 9 columns]

In [95]:
np.random.permutation(df.index) # burada indexlere göre rastgele döndürdük sayıları 

array([341,  20, 220, 138, 221, 336, 397,  61, 241, 352, 212, 168, 217,
       174, 354, 371, 356, 135, 375, 153, 291, 124, 344,  71, 249, 377,
       169, 389,  24,  91, 192,  92, 331, 362, 292,  32, 334, 342, 345,
       251, 295, 333,  13,  33,  12, 335, 347,  83,  58, 111, 164, 137,
        25,  34, 181, 358, 368, 159, 166, 154, 282, 396, 296, 273,  48,
       171, 259, 165, 268, 225, 254, 101, 284, 271, 176,  96,  40, 265,
       209, 206,  49, 394, 305, 112, 204, 133,  93, 172, 311, 230, 276,
       308, 309, 262, 391, 187,  52, 183, 373, 158,   7, 253,  70,  94,
       175, 231, 288, 361, 224, 196, 360, 190, 322,  42,  98, 155,  23,
       130,  16, 236, 323,  27, 283,  74, 232, 214,  19, 143, 229, 185,
       315,   9, 113, 267,  79, 118, 301, 353, 307, 219,  63, 247, 151,
       370, 382, 321, 395,  69, 293,  35, 281,  31, 378,  22, 379, 122,
       272, 367, 160, 131,  15,  11, 393, 252, 152, 302, 141,  53,  76,
       148, 286, 365, 357, 325,  95,   6, 233, 134,  36,  85, 15

In [96]:
np.random.permutation(10) # rastgele döndürür bir diziyi


array([9, 8, 6, 7, 2, 5, 3, 0, 1, 4])

### Converting a Dataframe to a Matrix

Sinir ağları doğrudan Python veri çerçeveleri üzerinde çalışmaz. Bir sinir ağı sayısal bir matris gerektirir. Program, verileri bir matrise dönüştürmek için bir veri çerçevesinin ** values ** özelliğini kullanır.

In [13]:
df.values
# bunu yapan şey numpy'dır 
# bir matris oluşturduğunu söyleyebilirim
# mesela aşağıda matris isim içeriyor o yüzden isim içermemesini istiyorsak

array([[20.2, 6, 232.0, ..., 79, 1, 'amc concord dl 6'],
       [14.0, 8, 304.0, ..., 74, 1, 'amc matador (sw)'],
       [14.0, 8, 351.0, ..., 71, 1, 'ford galaxie 500'],
       ...,
       [20.2, 6, 200.0, ..., 78, 1, 'ford fairmont (auto)'],
       [26.0, 4, 97.0, ..., 70, 2, 'volkswagen 1131 deluxe sedan'],
       [19.4, 6, 232.0, ..., 78, 1, 'amc concord']], dtype=object)

Yalnızca bazı sütunları dönüştürmek, ad sütununu dışarıda bırakmak için aşağıdaki kodu kullanmak isteyebilirsiniz.

In [14]:
df[['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin']].values
# 2 ayraç koyuyuoruz ki bunu bir dizi haline getirelim tek ayraç ile hata verecektir 

array([[ 20.2,   6. , 232. , ...,  18.2,  79. ,   1. ],
       [ 14. ,   8. , 304. , ...,  15.5,  74. ,   1. ],
       [ 14. ,   8. , 351. , ...,  13.5,  71. ,   1. ],
       ...,
       [ 20.2,   6. , 200. , ...,  15.8,  78. ,   1. ],
       [ 26. ,   4. ,  97. , ...,  20.5,  70. ,   2. ],
       [ 19.4,   6. , 232. , ...,  17.2,  78. ,   1. ]])

## Saving a Dataframe to CSV

Aşağıdaki kod bir karıştırma gerçekleştirir ve ardından yeni bir kopya kaydeder.

In [108]:
import os
import pandas as pd
import numpy as np

path = "." # buradaki nokta ise mevcut dizine eklemesi için aslında 

df = pd.read_csv(
    "auto-mpg.csv",
    na_values=['NA','?'])

filename_write = os.path.join(path, "auto-mpg-shuffle.csv")
df = df.reindex(np.random.permutation(df.index)) # dataframe'i karıştırıyoruz aslında burada tekrar yazıyoruz aynısını
# Satır numaralarını yazmamak için index = false belirtin
df.to_csv(filename_write, index=False) 
print("Done")

Done


In [109]:
ls
#dizindeki dosyalara bakabilirsin 

 Volume in drive C has no label.
 Volume Serial Number is 302D-B73D

 Directory of C:\Users\hp\Desktop\t81_558_deep_learning-2020-spring\t81_558_deep_learning-2020-spring

14.01.2021  15:33    <DIR>          .
14.01.2021  15:33    <DIR>          ..
23.08.2020  23:56             1.647 .gitignore
13.01.2021  20:19    <DIR>          .ipynb_checkpoints
14.12.2020  19:03    <DIR>          assignments
14.01.2021  12:20            18.121 auto-mpg.csv
14.01.2021  15:33            20.451 auto-mpg-shuffle.csv
23.08.2020  23:56            10.772 citations.bib
23.08.2020  23:56             3.351 CODE_OF_CONDUCT.md
23.08.2020  23:56    <DIR>          data
23.08.2020  23:56    <DIR>          images
23.08.2020  23:56    <DIR>          install
14.01.2021  15:32            71.245 Introduction to Pandas-2.1.ipynb
23.08.2020  23:56             6.699 jeffs_helpful.ipynb
23.08.2020  23:56            11.357 LICENSE
23.08.2020  23:56             7.108 manual_setup.ipynb
23.08.2020  23:56    <DIR>          pd

## Saving a Dataframe to Pickle

Çeşitli yazılım programları, CSV olarak depolanan metin dosyalarını kullanabilir. Ancak, oluşturulması daha uzun sürer ve bazen dönüşüm sırasında küçük miktarlarda hassasiyet kaybedebilirler. Diğer bir biçim [Pickle] (https://docs.python.org/3/library/pickle.html) şeklindedir. Genel olarak, CSV'ye çıktı verirsiniz çünkü Python dışında bile çok uyumludur. Aşağıdaki kod, Dataframe'den Pickle'a depolar.

In [110]:
import os
import pandas as pd
import numpy as np
import pickle

path = "."

df = pd.read_csv(
    "auto-mpg.csv",
    na_values=['NA','?'])

filename_write = os.path.join(path, "auto-mpg-shuffle.pkl")
df = df.reindex(np.random.permutation(df.index))

with open(filename_write,"wb") as fp:
    pickle.dump(df, fp)

pickle dosyasının belleğe geri yüklenmesi aşağıdaki kod satırları ile gerçekleştirilir. Dizin numaralarının hala önceki karıştırmadan karıştırıldığına dikkat edin. Yeniden oluşturulan CSV'yi yüklemek (son adımda) bu değerleri korumadı.

In [112]:
import os
import pandas as pd
import numpy as np
import pickle

path = "."

df = pd.read_csv(
    "auto-mpg.csv",
    na_values=['NA','?'])

filename_read = os.path.join(path, "auto-mpg-shuffle.pkl")

with open(filename_write,"rb") as fp:
    df = pickle.load(fp)

df.head()
# csv dosyası ile pickle dosyası arasındaki farkı şöyle anlayabiliriz, satır numaralarını rastgele koyuyor 
# çünkü biz yukarıda ki code'da onları karıştırıp koymuştuk o da bize bunu aynı şekilde tutuyor ama çokta bir esprisi yok diyebiliriz

mpg  cylinders  ...  origin                              name
9    15.0          8  ...       1                amc ambassador dpl
182  28.0          4  ...       2                          fiat 131
117  29.0          4  ...       2                          fiat 128
73   13.0          8  ...       1  chevrolet chevelle concours (sw)
180  25.0          4  ...       2                         saab 99le

[5 rows x 9 columns]